//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_input_ps linear v1.xyzw
dcl_output o0.xyzw
//
// Initial variable locations:
//   v0.x <- pixel.pos.x; v0.y <- pixel.pos.y; v0.z <- pixel.pos.z; v0.w <- pixel.pos.w; 
//   v1.x <- pixel.color.x; v1.y <- pixel.color.y; v1.z <- pixel.color.z; v1.w <- pixel.color.w; 
//   o0.x <- <main return value>.x; o0.y <- <main return value>.y; o0.z <- <main return value>.z; o0.w <- <main return value>.w
//
#line 9 "D:\Code\DX12-Atmosphere\DX12-Atmosphere\Testes\Shaders\FullScreenQuad_PS.hlsl"
mov o0.xyzw, v1.xyzw
ret 
// Approximately 2 instruction slots used
