//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer vertexBuffer
// {
//
//   float4x4 ProjectionMatrix;         // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// vertexBuffer                      cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xy          0     NONE   float   xy  
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[4], immediateIndexed
dcl_input v0.xy
dcl_input v1.xyzw
dcl_input v2.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_output o2.xy
dcl_temps 3
//
// Initial variable locations:
//   v0.x <- input.pos.x; v0.y <- input.pos.y; 
//   v1.x <- input.col.x; v1.y <- input.col.y; v1.z <- input.col.z; v1.w <- input.col.w; 
//   v2.x <- input.uv.x; v2.y <- input.uv.y; 
//   o2.x <- <main return value>.uv.x; o2.y <- <main return value>.uv.y; 
//   o1.x <- <main return value>.col.x; o1.y <- <main return value>.col.y; o1.z <- <main return value>.col.z; o1.w <- <main return value>.col.w; 
//   o0.x <- <main return value>.pos.x; o0.y <- <main return value>.pos.y; o0.z <- <main return value>.pos.z; o0.w <- <main return value>.pos.w
//
#line 23 "D:\Code\DX12-Atmosphere\DX12-Atmosphere\imgui\imgui_vert.hlsl"
mul r0.xyzw, v0.xxxx, cb0[0].xyzw
mul r1.xyzw, v0.yyyy, cb0[1].xyzw
add r0.xyzw, r0.xyzw, r1.xyzw
mul r1.xyzw, cb0[2].xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
add r0.xyzw, r0.xyzw, r1.xyzw
mul r1.xyzw, cb0[3].xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
add r0.xyzw, r0.xyzw, r1.xyzw  // r0.x <- output.pos.x; r0.y <- output.pos.y; r0.z <- output.pos.z; r0.w <- output.pos.w

#line 24
mov r1.xyzw, v1.xyzw  // r1.x <- output.col.x; r1.y <- output.col.y; r1.z <- output.col.z; r1.w <- output.col.w

#line 25
mov r2.xy, v2.xyxx  // r2.x <- output.uv.x; r2.y <- output.uv.y

#line 26
mov o0.xyzw, r0.xyzw
mov o1.xyzw, r1.xyzw
mov o2.xy, r2.xyxx
ret 
// Approximately 13 instruction slots used
